---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - filebeat

- name: configure elastic repo
  include_role:
    name: nephelaiio.elastic_repo
  when: filebeat_repo_manage | bool

- block:

    - name: install yum version lock support
      package:
        name: yum-plugin-versionlock
      when: ansible_os_family == 'RedHat'

    - name: disable yum package lock
      command: "yum versionlock delete {{ item }}"
      ignore_errors: yes
      loop: "{{ [filebeat_package_names] | flatten }}"
      when: ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

    - name: disable apt package lock
      command: "apt-mark unhold {{ item }}"
      loop: "{{ [filebeat_package_names] | flatten }}"
      when: ansible_os_family == 'Debian'

  when: filebeat_package_hold | bool
  ignore_errors: yes

- name: install filebeat elastic packages
  package:
    name: "{{ filebeat_package_names }}"
    state: "{{ filebeat_package_state }}"

- block:

    - name: enable apt package hold
      command: "apt-mark hold {{ item }}"
      loop: "{{ [filebeat_package_names] | flatten }}"
      when:
        - ansible_os_family == 'Debian'

    - name: enable yum package lock
      command: "yum versionlock add {{ item }}"
      loop: "{{ [filebeat_package_names] | flatten }}"
      when:
        - ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

  when: filebeat_package_hold | bool

- name: configure filebeat
  copy:
    content: |
      # Ansible managed

      {{ filebeat_conf | to_nice_yaml(indent=2) }}
    dest: "{{ filebeat_conf_path }}"
  notify: restart filebeat
  when: filebeat_conf_manage | bool

- name: manage filebeat services
  service:
    name: "{{ filebeat_service_name }}"
    state: "{{ filebeat_service_status }}"
    enabled: "{{ filebeat_service_enabled }}"
